USE master
IF EXISTS (SELECT * FROM SYSDATABASES WHERE NAME = 'ManagerStudent')
			Drop database ManagerStudent
			
CREATE DATABASE ManagerStudent
go
use ManagerStudent

CREATE TABLE KHOA (
	MaKhoa CHAR(4) PRIMARY KEY,
	TenKhoa NVARCHAR(30),
);
CREATE TABLE KHOAHOC(
	MaKH CHAR(4) Primary key,
	TenKH NVARCHAR(30),
);
CREATE TABLE TINHTRANGHOC(
	ID_Status Char(1) Primary key,
	TinhTrang NVARCHAR(30),
);
CREATE TABLE SINHVIEN (
	MaSV CHAR(10) PRIMARY KEY,
	HoTen NVARCHAR(50),
	GioiTinh BIT,
	DiaChi NVARCHAR(100),
	NienKhoa CHAR(9),
	CMND CHAR(12),
	SoDienThoai CHAR(10),
	Email VARCHAR(MAX),
	NgaySinh DATE,
	MatKhau VARCHAR(MAX),
	MaKhoa CHAR(4),
	MaKH CHAR(4),
	ID_Status Char(1),
	[Role] NVARCHAR(25),
	CONSTRAINT FK_SV_K FOREIGN KEY (MaKhoa)
	REFERENCES KHOA (MaKhoa),
	CONSTRAINT FK_SV_KH FOREIGN KEY (MaKH)
	REFERENCES KHOAHOC (MaKH),
	CONSTRAINT FK_SV_TT FOREIGN KEY (ID_Status)
	REFERENCES TINHTRANGHOC (ID_Status)
)


CREATE TABLE MONHOC(
	MaMH CHAR(4) PRIMARY KEY,
	TenMH NVARCHAR(50),
	SoTinChi INT,
	MaKhoa CHAR(4),
	CONSTRAINT FK_MH_K FOREIGN KEY (MaKhoa)
	REFERENCES KHOA(MaKhoa)
)


CREATE TABLE GIANGVIEN(
	MaGV CHAR(4) PRIMARY KEY,
	HoTen NVARCHAR(50),
	GioiTinh BIT,
	SoDienThoai CHAR(10),
	Email CHAR(20),
	ChucVu NVARCHAR(20),
	MatKhau VARCHAR(MAX),
	NgaySinh DATE,
	NgayVaoLam DATE,
	DiaChi NVARCHAR(50),
	MaKhoa CHAR(4),
	CONSTRAINT FK_GV_K FOREIGN KEY (MaKhoa)
	REFERENCES KHOA (MaKhoa),
)
CREATE TABLE LOPHOCPHAN(
	MaLHP CHAR(4) PRIMARY KEY,
	TenLHP NVARCHAR(50),
	CaHoc INT,
	Siso INT,
	HK INT,
	MaGV CHAR(4),
	MaMH CHAR(4),
	CONSTRAINT FK_LHP_MH FOREIGN KEY (MaMH)
	REFERENCES MONHOC (MaMH),
	CONSTRAINT FK_LHP_GV FOREIGN KEY (MaGV)
	REFERENCES GIANGVIEN (MaGV)
)
CREATE TABLE Diem(
	MaSV CHAR(10),
	MaLHP CHAR(4),
	DiemChuyenCan INT,
	DiemGiuaKy INT,
	DiemCuoiKy INT,
	CONSTRAINT PK_DK PRIMARY KEY (MaSV, MaLHP),
	CONSTRAINT FK_DK_SV FOREIGN KEY (MaSV)
	REFERENCES SINHVIEN (MaSV),
	CONSTRAINT FK_DK_LHP FOREIGN KEY (MaLHP)
	REFERENCES LOPHOCPHAN (MaLHP)
)
CREATE TABLE ADMIN_ACCOUNT(
	MaAd CHAR(5) PRIMARY KEY,
	MatKhau VARCHAR(MAX)
)

INSERT INTO ADMIN_ACCOUNT VALUES('admin','123')


-- TẠO TRIGGER
CREATE TRIGGER tg_MatKhauSV 
ON SINHVIEN
AFTER INSERT
AS
BEGIN
	DECLARE @NgaySinh DATE, @MaSV CHAR(4), @String VARCHAR(MAX), @MatKhau VARCHAR(MAX), @Day VARCHAR(MAX), @Month VARCHAR(MAX),@DAY_STRING VARCHAR(MAX),@MONTH_STRING VARCHAR(MAX)
	SELECT @NgaySinh = NgaySinh, @MaSV = MaSV FROM inserted  
	IF DAY(@NgaySinh) < 10 
	BEGIN
		SET @Day = '0'+Convert(CHAR,DAY(@NgaySinh))
		SELECT @DAY_STRING = REPLACE(@Day, ' ', '') 
	END
	ELSE
	BEGIN
		SET @Day = Convert(CHAR,DAY(@NgaySinh))
		SELECT @DAY_STRING = REPLACE(@Day, ' ', '') 
	END

	IF MONTH(@NgaySinh) < 10 
	BEGIN
		SET @Month = '0'+Convert(CHAR,MONTH(@NgaySinh))
		SELECT @MONTH_STRING = REPLACE(@Month, ' ', '') 
	END
	ELSE
	BEGIN
		SET @Month = Convert(CHAR,MONTH(@NgaySinh))
		SELECT @MONTH_STRING = REPLACE(@Month, ' ', '') 
	END
	SET @String = @DAY_STRING + @MONTH_STRING+Convert(CHAR,YEAR(@NgaySinh))
	SELECT @MatKhau = REPLACE(@string, ' ', '') 
	UPDATE SINHVIEN 
	SET MatKhau = @MatKhau
	WHERE MaSV = @MaSV
END
drop trigger tg_MatKhauSV

INSERT INTO 
INSERT INTO SINHVIEN VALUES('SV02', N'Trần Văn C', 1, N'789 Đường C, Quận 3, TP.HCM', '2021-2025', '0934567890', 'tranvanc@example.com', '2002-03-25', null, NULL, Null, Null, Null)
SELECT * FROM SINHVIEN


