//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diem
    {
        public string MaSV { get; set; }
        public string MaLHP { get; set; }
        public Nullable<int> DiemChuyenCan { get; set; }
        public Nullable<int> DiemGiuaKy { get; set; }
        public Nullable<int> DiemCuoiKy { get; set; }
    
        public virtual LOPHOCPHAN LOPHOCPHAN { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
