//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOPHOCPHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOPHOCPHAN()
        {
            this.Diems = new HashSet<Diem>();
        }
    
        public string MaLHP { get; set; }
        public string TenLHP { get; set; }
        public Nullable<int> CaHoc { get; set; }
        public Nullable<int> Siso { get; set; }
        public Nullable<int> HK { get; set; }
        public string MaGV { get; set; }
        public int MaMH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diem> Diems { get; set; }
        public virtual GIANGVIEN GIANGVIEN { get; set; }
        public virtual MONHOC MONHOC { get; set; }
    }
}
