//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MONHOC()
        {
            this.LOPHOCPHANs = new HashSet<LOPHOCPHAN>();
        }
    
        public int MaMH { get; set; }
        public string TenMH { get; set; }
        public Nullable<int> SoTinChi { get; set; }
        public string MaKhoa { get; set; }
        public Nullable<int> SoTinChiLyThuyet { get; set; }
        public Nullable<int> SoTinChiThucHanh { get; set; }
    
        public virtual KHOA KHOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOPHOCPHAN> LOPHOCPHANs { get; set; }
    }
}
