//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONHOC
    {
        public int MaMH { get; set; }
        public string TenMH { get; set; }
        public Nullable<int> SoTinChi { get; set; }
        public string MaKhoa { get; set; }
        public Nullable<int> SoTinChiLyThuyet { get; set; }
        public Nullable<int> SoTinChiThucHanh { get; set; }
        public string MaLHP { get; set; }
    
        public virtual KHOA KHOA { get; set; }
        public virtual ICollection<LOPHOCPHAN> LOPHOCPHANs { get; set; }
    }
}
